CREATE OR REPLACE PROCEDURE  allowances_addition(empid in EMPLOYEE.EMPID%TYPE)
IS
CURSOR  C IS SELECT TYPE FROM ALLOWANCES ;
VAR C%ROWTYPE;
A_AMOUNT employee_allowance.ALLOW_AMOUNT%TYPE;
ALL_ID ALLOWANCES.ALLOWANCEID%TYPE;
ATYPE ALLOWANCES.TYPE%TYPE;
BEGIN
OPEN C;
LOOP
FETCH C INTO VAR;
EXIT WHEN C%NOTFOUND;
 dbms_output.put_line(VAR.TYPE);
END LOOP;
CLOSE C;
ATYPE :='&ALLOWANCE_TYPE';
SELECT ALLOWANCEID INTO ALL_ID FROM ALLOWANCES WHERE TYPE =ATYPE ;
A_AMOUNT := ALLOWANCE_AMOUNT(ATYPE);
INSERT INTO  employee_allowance VALUES(EMPID,ALL_ID,TO_DATE(SYSDATE,'DD-MM-YYYY'),A_AMOUNT);
END;
/
 

CREATE OR REPLACE FUNCTION ALLOWANCE_AMOUNT(ATYPE ALLOWANCES.TYPE%TYPE )
RETURN NUMBER
IS
BEGIN
IF UPPER(ATYPE)=UPPER('MEDICAL') THEN
RETURN 3000;
ELSIF 
UPPER(ATYPE)=UPPER('house_rent') THEN
RETURN 5000;
ELSIF 
UPPER(ATYPE)=UPPER('overtime') THEN
RETURN 6000;
ELSIF 
UPPER(ATYPE)=UPPER('special_allowance') THEN
RETURN 2000;
ELSIF 
UPPER(ATYPE)=UPPER('meal') THEN
RETURN 4000;
ELSE
RETURN 3000;
END IF;
END;
