

--LOCATION TABLE

Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('B1000','TECH PARK','BENGALURU','KARNATAKA','INDIA');
Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('B1014','PRITECH PARK','BENGALURU','KARNATAKA','INDIA');

Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('M1002','SUPERTECH PARK','MUMBAI','MAHARASHTRA','INDIA');
Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('M1010','CENTRAL BUILDING','NAGPUR','MAHARASHTRA','INDIA');
Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('M1019','COMMERZONE PARK','PUNE','MAHARASHTRA','INDIA');

Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('T1001','JUBILEE HILLS','HYDERABAD','TELANGANA','INDIA');
Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('T1021','DLF CYBERCITY','HYDERABAD','TELANGANA','INDIA');

Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('N1003','OXYGEN BUSINESS PARK','NULL','NEW DELHI','INDIA');

Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('N1015','NOIDA EXPRESSWAY','NOIDA','UTTAR PRADESH','INDIA');

Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('H1000','DLF CYBERCITY','GURUGRAM','HARYANA','INDIA');

Insert into LOCATION (LOCATIONID,BRANCH_NAME,CITY,STATE,COUNTRY)  values ('C1004','RMZ MILLENIA','CHENNAI','TAMIL NADU','INDIA');









